name:                process-escape-windows
version:             0.1.0.0
github:              "githubuser/process-escape-windows"
license:             BSD-3-Clause
author:              "Tom McLaughlin"
maintainer:          "tom@codedown.io"

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- base >= 4.7 && < 5
- Win32

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- LambdaCase
- QuasiQuotes

library:
  source-dirs: src

executables:
  process-escape-windows-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - process-escape-windows

tests:
  tests:
    main:                Spec.hs
    source-dirs:
    - test
    - test-lib
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - process-escape-windows
    - sandwich
    - string-interpolate
    - unliftio
    - QuickCheck
